services:
  backend:
    build: .
    image: backend-bun-image:v1
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
    container_name: backend-bun-container
    command: bun run dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json