services:
  backend:
    build: .
    image: backend-bun-image:v1
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    container_name: backend-bun-container