services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-bun-image:v1
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    container_name: backend-bun-container
    develop:
      watch:
        - action: sync
          path: . 
          target: /src/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json